package com.univr.diabetes_logger.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.univr.diabetes_logger.model.Patient;
import com.univr.diabetes_logger.repository.PatientRepository;

/**
 * PatientController
 */
@RestController // This means that this class is a Controller
@RequestMapping(path = "/patients") // This means URL's start with /demo (after Application path)
public class PatientController {
  @Autowired // This means to get the bean called patientRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private PatientRepository patientRepository;

  @GetMapping
  public Iterable<Patient> getAllPatients() {
    return patientRepository.findAll();
  }

  @GetMapping("/{id}")
  public Patient getPatient(@PathVariable Integer id) {
    return patientRepository.findById(id).orElse(null);
  }

  @PostMapping
  public Patient createPatient(@RequestBody Patient patient) {
    return patientRepository.save(patient);
  }
}
