package com.univr.diabetes_logger.controller;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import com.univr.diabetes_logger.model.Patient;
import com.univr.diabetes_logger.service.PatientService;

/**
 * PatientController
 */
@RestController // This means that this class is a Controller
@RequestMapping(path = "/patients") // This means URL's start with /demo (after Application path)
public class PatientController {
  @Autowired // This means to get the bean called patientRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private PatientService patientService;

  public PatientController(PatientService patientService) {
    this.patientService = patientService;
  }

  @GetMapping
  public List<Patient> getAllPatients() {
    return patientService.getAllPatients();
  }

  @GetMapping("/{id}")
  public Optional<Patient> getPatient(@PathVariable Integer id) {
    return patientService.getPatientById(id);
  }

  @PostMapping
  @ResponseStatus(HttpStatus.CREATED)
  public Patient createPatient(@RequestBody Patient patient) {
    return patientService.createPatient(patient);
  }
}
