package com.univr.diabetes_logger.controller;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.util.UriComponentsBuilder;

import com.univr.diabetes_logger.model.Medic;
import com.univr.diabetes_logger.service.MedicService;
import org.springframework.web.bind.annotation.PutMapping;

/**
 * MedicController
 */
@RestController // This means that this class is a Controller
@RequestMapping(path = "/reports") // This means URL's start with /medics (after Application path)
public class ReportController {
    @Autowired // This means to get the bean called medicRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ReportService reportService;

    public ReportController(MedicService medicService) {
        this.medicService = medicService;
    }


}
